-- 1. Create Referrals Table
create table referrals (
  id bigint generated by default as identity primary key,
  patient_id bigint references patients(id),
  from_hospital_id bigint references hospitals(id),
  to_hospital_id bigint references hospitals(id),
  status text check (status in ('pending', 'accepted', 'rejected')) default 'pending',
  priority text default 'normal',
  notes text,
  clinical_summary jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. Update Patients Table to belong to a specific hospital
-- (We default existing patients to Hospital 1 to avoid breaking current view)
alter table patients 
add column if not exists hospital_id bigint references hospitals(id) default 1;

-- 3. Enable Realtime for Referrals (Critical for the "Instant Popup")
alter publication supabase_realtime add table referrals;
