-- 1. Create Hospitals Table (Simulating the City Network)
create table hospitals (
  id bigint generated by default as identity primary key,
  name text not null,
  status text check (status in ('optimal', 'busy', 'critical', 'offline')) default 'optimal',
  load_percentage int default 0, -- 0 to 100
  wait_time_min int default 0,
  distance_km numeric(4,1) default 0.0,
  specializations text[] default '{}',
  updated_at timestamptz default now()
);

-- 2. Insert Mock Hospitals (So you have a "Network" to show)
insert into hospitals (name, status, load_percentage, wait_time_min, distance_km, specializations)
values 
  ('General City Hospital', 'busy', 78, 45, 2.5, '{trauma,cardio}'),
  ('Westside Urgent Care', 'optimal', 30, 10, 5.2, '{general,pediatrics}'),
  ('Memorial Trauma Center', 'critical', 95, 120, 8.0, '{trauma,neurology}');

-- 3. Update Patients table to support Transfer logic
alter table patients 
add column if not exists redirect_recommended boolean default false,
add column if not exists redirect_hospital_id bigint references hospitals(id);

-- 4. Enable Realtime for Hospitals (So the dashboard updates live)
alter publication supabase_realtime add table hospitals;
